### PR TITLE
UBERON parcellation

### PR DESCRIPTION
**Pull request by UlrikeS91**
These is the first PR for the UBERON parcellations.
I've done the following: 
1. I used this as starting point: https://raw.githubusercontent.com/obophenotype/uberon/master/subsets/nervous-minimal.obo
2. Transformed them to fit our structure with: `name` = name, `definition` = definition (made slightly prettier but they are still not pretty), `description` = Generic text from the is_a-property and relation-property & `ontologyIdentifier` = id.
3. Made a subset with only UBERON terms (were the ontology ID has "UBERON:xxxxxx").
4. Compared with the ones @olinux already added in the old KGE (under "Ontologies" --> "Brain") with this list. 
5. Exported JSON-LDs 

The minimal nervous system ontology has 3213terms, from which 2862 terms have UBERON IDs. In the KG (ontologies --> brain), we only had 467 terms. This PR has 432 terms. I don't know why there are 35 terms fewer, but my guess is that those are terms that are duplicated and/or terms that don't have UBERON IDs. 

I'm ready to push another PR with the next 639 terms as soon as this one is accepted. These are additional UBERON terms that seem relevant for our UBERONParcellation. More about that later.

### CODE REVIEW

**Review by lzehl — APPROVED** [review]
quickly went through them. @UlrikeS91 thanks for the work. We need to see over time how much is missing or which one could be kicked out.

**Comment by UlrikeS91** [comment]
> quickly went through them. @UlrikeS91 thanks for the work. We need to see over time how much is missing or which one could be kicked out.

Well, I have another 639 terms that I think could be relevant. I can make a new PR with those. I just didn't want to mix up what was already in the old KG and what I think should be there too ;)

**Comment by lzehl** [comment]
Wait with the new PR until I've made the changes to the controlledTerms (I'll try to push this through this week).

**Comment by lzehl** [comment]
But after that: happy to look through another large set of terms :sweat_smile:

**Pull request merged**
