### PR TITLE
updating "qualitative overlaps"

### PR DESCRIPTION
**Pull request by lzehl**
as discussed (tried to provide also definitions this time)

### CODE REVIEW

**Comment by lzehl** [comment]
@UlrikeS91 the definition for "isLexicalVariantOf" might still need some work / feedback from Heidi, Ingvild (and/or Tom @tgbugs).

**Comment by tgbugs** [comment]
What is the use case for `isLexicalVariantOf`? In what cases would the terms not be merged and one marked as a synonym?

A side point `isIdenticalTo` is probably better grammatically, "identical with" is not a normal construction in English.

**Comment by lzehl** [comment]
@tgbugs : 

"isLexicalVariantOf" was a suggestion for the terms that are "just known" to be the very similar/the same but were actually not visually compared. Heidi might be able to give a good example, but as far as I understood it: "hOc1" of the Julich-Brain which would be lexical variant of "Brodmann Area 17" (because historically it is known, but annotations were actually not visually compared).

I thought in English "is identical to" means "is the same thing" while "is identical with" would rather mean "looks the same as". If that distinction is wrong I'm happy to change it back to "is identical to" :wink:

**Comment by tgbugs** [comment]
In my mind `isLexicalVariantOf` implies that the same delineation criteria are used. Given that the Brodmann criteria are no longer available this would suggest that we might want something more than just a lexical variant ... maybe something like `modernReinterpretationOf` or `attemptToRecaptureTheSameRegionAs`? Too specific to the exact example, but something about the fact that we are trying to delineate the same region as previously described in another source.

Ah, I see. Hrm. Maybe `visuallyIdenticalTo` so that it is clear that we are talking about visual comparison, or maybe `spatiallyIdenticalTo` to deconflate the method of comparison and deal only with the data modality for the comparison?

**Comment by ingvildeb** [comment]
As Lyuba says, the idea of the "isLexicalVariantOf" is for cases when one would assume - based on the name - that two annotations represent the same region, but this has not been confirmed by visual or spatial comparison. In rodent atlases, we have a lot of cases where lexical variants exist across different atlases, but it does not necessarily mean that they are represent identical regions (I would say they typically don't). There are also some examples where lexical variants are used for completely different areas. So while lexical variants often have some qualitative overlap (and in some cases are identical), this is not always the case. Whether or not the same delineation criteria are used would be a good indicator, but is unfortunately often very difficult to assess due to lack of descriptions in most atlases.

If we were strict, we would not register a "qualitative overlap" record unless a visual or spatial comparison of two annotations have been performed, but this is actually a huge effort to do across all the regions and atlases available. We will probably _have to_ add a lot of relationships based on just assessment of the names and general knowledge about how such names normally relate across atlases. This makes it very important to keep track of the method of comparison.

But I agree something is not quite right with having isLexicalVariantOf as a relationship type. Perhaps we should rather add this to the "criteria quality type", so that there are qualitative, quantitative, and lexical assessments? Or maybe it would be better to then use visual, spatial and lexical assessments? Each of these types of assessments could lead to a qualitative overlap of the types "Is subset of", "Is superset of", "Is identical to", or "Overlaps with".

**Comment by lzehl** [comment]
@tgbugs and @ingvildeb and @aeidi89 we need to come to an agreement with this PR.

In summary the terms "is identical to", "is subset of", "is superset of", "has intersection with" and "is lexical variant of" were introduced to define the qualitative overlap assessment between two parcellation entities.

The quantitative assessment schema will not refer to these terms because it will provide a quantified overlap. 

Should the "is lexical variant of" be deleted or should we rename it? Would we actually make use of this term?

**Comment by ingvildeb** [comment]
I think we can and should make use of this term, but I don't think it's ideal to have it as a qualitative overlap (ref. my comment above). Again, I think it would make more sense to have it as a criteria quality type, i.e. as the most basic level of comparing two regions (based on name only). Whenever a qualitative or quantitative assessment has been done, that would be preferable, but it will not always be available.

**Comment by lzehl** [comment]
@ingvildeb I don't think it's a criteria quality type either... 

Criteria quality types are used for describing the quality of the process of defining a single annotation which can be either "processive" and "asserted". In contrast the "is lexical variant of" is a comparison between two defined Parcellation Entities (or their annotations). 

I would maybe kick the term out for now, and we can reconsider it when we have to handle a respective use case.
Would that be okay with everyone? (@ingvildeb, @tgbugs , @UlrikeS91 , @aeidi89 )

**Comment by tgbugs** [comment]
I think `is lexical variant of` should not be included because it is too easy to misunderstand what it is trying to capture, it is not a synonym. It is closer to the old NeuroLex relationship `partially overlaps`. It also does not fit as criteria for the reasons @lzehl mentions. I think `overlaps with` is the only meaningful version of this that we might try.

**Comment by lzehl** [comment]
@tgbugs "partiallyOverlapsWith" in addition to "hasIntersectionWith" or instead? If both are kept, what is the difference between them?

**Comment by tgbugs** [comment]
They both mean the same thing, but overlaps is more spatial in its connotation. I would go with `partiallyOverlapsWith` but either works. I would not keep both.

**Comment by lzehl** [comment]
@tgbugs thanks. I'll deleted now the lexical variant and changed the other into partiallyOverlapsWith. If there are no further issues (typos) feel free to merge the PR.

@ingvildeb we can discuss again where the lexical variant should be reintroduced if we come across a respective use case.

**Pull request merged**
